export const SUPPORTED_LANGUAGES = [
  { code: 'en', name: 'English', native: 'English', flag: '🇺🇸', dir: 'ltr' },
  { code: 'es', name: 'Spanish', native: 'Español', flag: '🇪🇸', dir: 'ltr' },
  { code: 'fr', name: 'French', native: 'Français', flag: '🇫🇷', dir: 'ltr' },
  { code: 'de', name: 'German', native: 'Deutsch', flag: '🇩🇪', dir: 'ltr' },
  { code: 'pt', name: 'Portuguese', native: 'Português', flag: '🇵🇹', dir: 'ltr' },
  { code: 'it', name: 'Italian', native: 'Italiano', flag: '🇮🇹', dir: 'ltr' },
  { code: 'zh', name: 'Chinese', native: '中文', flag: '🇨🇳', dir: 'ltr' },
  { code: 'ja', name: 'Japanese', native: '日本語', flag: '🇯🇵', dir: 'ltr' },
  { code: 'ko', name: 'Korean', native: '한국어', flag: '🇰🇷', dir: 'ltr' },
  { code: 'ar', name: 'Arabic', native: 'العربية', flag: '🇸🇦', dir: 'rtl' },
  { code: 'hi', name: 'Hindi', native: 'हिन्दी', flag: '🇮🇳', dir: 'ltr' },
  { code: 'ru', name: 'Russian', native: 'Русский', flag: '🇷🇺', dir: 'ltr' },
  { code: 'tr', name: 'Turkish', native: 'Türkçe', flag: '🇹🇷', dir: 'ltr' },
  { code: 'vi', name: 'Vietnamese', native: 'Tiếng Việt', flag: '🇻🇳', dir: 'ltr' },
  { code: 'nl', name: 'Dutch', native: 'Nederlands', flag: '🇳🇱', dir: 'ltr' },
];

export type LangCode = typeof SUPPORTED_LANGUAGES[number]['code'];

const DEFAULT_LANG: LangCode = 'en';
const DICT: Record<string, Record<string, string>> = {};

function add(k: string, en: string, es: string, fr: string, de: string, pt: string, it: string, zh: string, ja: string, ko: string, ar: string, hi: string, ru: string, tr: string, vi: string, nl: string) {
  DICT[k] = { en, es, fr, de, pt, it, zh, ja, ko, ar, hi, ru, tr, vi, nl };
}

add('tx_receipt','Transaction Receipt','Recibo de Transacción','Reçu de Transaction','Transaktionsbeleg','Recibo de Transação','Ricevuta di Transazione','交易收据','取引領収書','거래 영수증','إيصال المعاملة','लेनदेन रसीद','Квитанция','İşlem Makbuzu','Biên lai Giao dịch','Transactiebon');
add('tx_failed','Transaction Failed','Transacción Fallida','Transaction Échouée','Transaktion Fehlgeschlagen','Transação Falhou','Transazione Fallita','交易失败','取引失敗','거래 실패','فشلت المعاملة','लेनदेन विफल','Ошибка транзакции','İşlem Başarısız','Giao dịch Thất bại','Transactie Mislukt');
add('tx_pending','Transaction Pending','Transacción Pendiente','Transaction en Attente','Transaktion Ausstehend','Transação Pendente','Transazione in Sospeso','交易待处理','取引保留中','거래 보류 중','المعاملة معلقة','लेनदेन लंबित','Транзакция в ожидании','İşlem Beklemede','Giao dịch Đang chờ','Transactie in Afwachting');
add('tx_on_hold','Transaction On Hold','Transacción en Espera','Transaction en Attente','Transaktion Zurückgestellt','Transação em Espera','Transazione in Attesa','交易暂停','取引保留','거래 대기 중','المعاملة معلقة','लेनदेन होल्ड पर','Транзакция приостановлена','İşlem Beklemede','Giao dịch Tạm dừng','Transactie On Hold');
add('tx_processing','Transaction Processing','Procesando Transacción','Transaction en Cours','Transaktion wird Bearbeitet','Processando Transação','Transazione in Elaborazione','交易处理中','取引処理中','거래 처리 중','جاري معالجة المعاملة','लेनदेन प्रसंस्करण में','Обработка транзакции','İşlem İşleniyor','Giao dịch Đang xử lý','Transactie wordt Verwerkt');
add('payment_successful','Payment Successful','Pago Exitoso','Paiement Réussi','Zahlung Erfolgreich','Pagamento Bem-sucedido','Pagamento Riuscito','付款成功','支払い完了','결제 성공','تم الدفع بنجاح','भुगतान सफल','Платеж выполнен','Ödeme Başarılı','Thanh toán Thành công','Betaling Geslaagd');
add('payment_failed','Payment Failed','Pago Fallido','Paiement Échoué','Zahlung Fehlgeschlagen','Pagamento Falhou','Pagamento Fallito','付款失败','支払い失敗','결제 실패','فشل الدفع','भुगतान विफल','Платеж не удался','Ödeme Başarısız','Thanh toán Thất bại','Betaling Mislukt');
add('payment_pending','Payment Pending','Pago Pendiente','Paiement en Attente','Zahlung Ausstehend','Pagamento Pendente','Pagamento in Sospeso','付款待处理','支払い保留中','결제 보류 중','الدفع معلق','भुगतान लंबित','Платеж в ожидании','Ödeme Beklemede','Thanh toán Đang chờ','Betaling in Afwachting');
add('tx_desc_success','Your transaction has been processed successfully.','Su transacción ha sido procesada exitosamente.','Votre transaction a été traitée avec succès.','Ihre Transaktion wurde erfolgreich verarbeitet.','Sua transação foi processada com sucesso.','La sua transazione è stata elaborata con successo.','您的交易已成功处理。','取引が正常に処理されました。','거래가 성공적으로 처리되었습니다.','تمت معالجة معاملتك بنجاح.','आपका लेनदेन सफलतापूर्वक संसाधित हो गया है।','Ваша транзакция успешно обработана.','İşleminiz başarıyla işlendi.','Giao dịch của bạn đã được xử lý thành công.','Uw transactie is succesvol verwerkt.');
add('tx_desc_failed','Your transaction could not be processed. Please contact support.','Su transacción no pudo ser procesada. Contacte soporte.','Votre transaction n\'a pas pu être traitée. Contactez le support.','Ihre Transaktion konnte nicht verarbeitet werden. Kontaktieren Sie den Support.','Sua transação não pôde ser processada. Entre em contato com o suporte.','La sua transazione non è stata elaborata. Contatti l\'assistenza.','您的交易无法处理。请联系客服。','取引を処理できませんでした。サポートにお問い合わせください。','거래를 처리할 수 없습니다. 지원팀에 문의하세요.','لم نتمكن من معالجة معاملتك. يرجى الاتصال بالدعم.','आपका लेनदेन संसाधित नहीं किया जा सका। कृपया सहायता से संपर्क करें।','Ваша транзакция не может быть обработана. Свяжитесь со службой поддержки.','İşleminiz işlenemedi. Lütfen destek ekibiyle iletişime geçin.','Giao dịch của bạn không thể được xử lý. Vui lòng liên hệ hỗ trợ.','Uw transactie kon niet worden verwerkt. Neem contact op met de ondersteuning.');
add('tx_desc_pending','Your transaction is currently pending approval.','Su transacción está pendiente de aprobación.','Votre transaction est en attente d\'approbation.','Ihre Transaktion wartet auf Genehmigung.','Sua transação está pendente de aprovação.','La sua transazione è in attesa di approvazione.','您的交易目前正在等待批准。','取引は現在承認待ちです。','거래가 현재 승인 대기 중입니다.','معاملتك قيد انتظار الموافقة حالياً.','आपका लेनदेन वर्तमान में अनुमोदन के लिए लंबित है।','Ваша транзакция в настоящее время ожидает одобрения.','İşleminiz şu anda onay bekliyor.','Giao dịch của bạn hiện đang chờ phê duyệt.','Uw transactie wacht momenteel op goedkeuring.');
add('tx_desc_onhold','Your transaction is on hold. Please contact support for more information.','Su transacción está en espera. Contacte soporte para más información.','Votre transaction est en attente. Contactez le support pour plus d\'informations.','Ihre Transaktion ist zurückgestellt. Kontaktieren Sie den Support.','Sua transação está em espera. Entre em contato com o suporte.','La sua transazione è in attesa. Contatti l\'assistenza.','您的交易已暂停。请联系客服获取更多信息。','取引は保留中です。詳細についてはサポートにお問い合わせください。','거래가 보류되었습니다. 자세한 내용은 지원팀에 문의하세요.','معاملتك معلقة. يرجى الاتصال بالدعم للمزيد من المعلومات.','आपका लेनदेन होल्ड पर है। अधिक जानकारी के लिए कृपया सहायता से संपर्क करें।','Ваша транзакция приостановлена. Свяжитесь со службой поддержки.','İşleminiz beklemeye alındı. Daha fazla bilgi için lütfen destek ekibiyle iletişime geçin.','Giao dịch của bạn đang tạm dừng. Vui lòng liên hệ hỗ trợ.','Uw transactie is on hold. Neem contact op met de ondersteuning.');
add('tx_desc_processing','Your transaction is currently being processed.','Su transacción está siendo procesada.','Votre transaction est actuellement en cours de traitement.','Ihre Transaktion wird derzeit bearbeitet.','Sua transação está sendo processada.','La sua transazione è attualmente in elaborazione.','您的交易正在处理中。','取引は現在処理中です。','거래가 현재 처리 중입니다.','معاملتك قيد المعالجة حالياً.','आपका लेनदेन वर्तमान में संसाधित किया जा रहा है।','Ваша транзакция в настоящее время обрабатывается.','İşleminiz şu anda işleniyor.','Giao dịch của bạn hiện đang được xử lý.','Uw transactie wordt momenteel verwerkt.');

add('recipient','Recipient','Destinatario','Destinataire','Empfänger','Destinatário','Destinatario','收款人','受取人','수신인','المستلم','प्राप्तकर्ता','Получатель','Alıcı','Người nhận','Ontvanger');
add('date','Date','Fecha','Date','Datum','Data','Data','日期','日付','날짜','التاريخ','तारीख','Дата','Tarih','Ngày','Datum');
add('reference_id','Reference ID','ID de Referencia','ID de Référence','Referenz-ID','ID de Referência','ID di Riferimento','参考编号','参照ID','참조 ID','معرف المرجع','संदर्भ आईडी','Идентификатор','Referans Kimliği','Mã tham chiếu','Referentie ID');
add('status','Status','Estado','Statut','Status','Status','Stato','状态','ステータ스','상태','الحالة','स्थिति','Статус','Durum','Trạng thái','Status');
add('usd_amount','USD Amount','Monto USD','Montant USD','USD-Betrag','Valor USD','Importo USD','美元金额','USD金額','USD 금액','مبلغ الدولار','यूएसडी राशि','Сумма USD','USD Tutarı','Số tiền USD','USD Bedrag');
add('view_details','View details','Ver detalles','Voir les détails','Details anzeigen','Ver detalhes','Visualizza dettagli','查看详情','詳細を表示','자세히 보기','عرض التفاصيل','विवरण देखें','Посмотреть детали','Detayları görüntüle','Xem chi tiết','Bekijk details');
add('questions_ref_id','If you have questions, please quote the reference ID.','Si tiene preguntas, cite el ID de referencia.','Si vous avez des questions, veuillez citer l\'ID de référence.','Bei Fragen nennen Sie bitte die Referenz-ID.','Se tiver dúvidas, cite o ID de referência.','In caso di domande, si prega di citare l\'ID di riferimento.','如有疑问，请注明参考编号。','ご質問がある場合は、参照IDを引用してください。','질문이 있으면 참조 ID를 인용하십시오.','إذا كانت لديك أي أسئلة، يرجى ذكر معرف المرجع.','यदि आपके कोई प्रश्न हैं， तो कृपया संदर्भ आईडी उद्धृत करें।','Если у вас есть вопросы, укажите идентификатор.','Sorularınız varsa lütfen referans kimliğini belirtin.','Nếu có thắc mắc, vui lòng trích dẫn mã tham chiếu.','Als u vragen heeft, vermeld dan het referentie-ID.');

add('support_replied','Support Has Replied','Soporte Ha Respondido','Le Support a Répondu','Support Hat Geantwortet','Suporte Respondeu','Il Supporto Ha Risposto','客服已回复','サポートが返信しました','지원팀이 답변했습니다','رد فريق الدعم','सहायता ने जवाब दिया','Поддержка ответила','Destek Yanıt Verdi','Hỗ trợ Đã Trả lời','Support Heeft Gereageerd');
add('support_replied_desc','our support team has responded to your live chat message.','nuestro equipo de soporte ha respondido a su mensaje de chat en vivo.','notre équipe de support a répondu à votre message de chat en direct.','unser Support-Team hat auf Ihre Live-Chat-Nachricht geantwortet.','nossa equipe de suporte respondeu à sua mensagem de chat ao vivo.','il nostro team di supporto ha risposto al tuo messaggio di chat dal vivo.','我们的客服团队已回复您的实时聊天消息。','サポートチームがライブチャットメッセージに返信しました。','지원팀이 라이브 채팅 메시지에 답변했습니다.','رد فريق الدعم على رسالتك في الدردشة المباشرة.','हमारी सहायता टीम ने आपके लाइव चैट संदेश का जवाब दिया है।','наша служба поддержки ответила на ваше сообщение в чате.','destek ekibimiz canlı sohbet mesajınıza yanıt verdi.','đội ngũ hỗ trợ của chúng tôi đã phản hồi tin nhắn trò chuyện trực tiếp của bạn.','ons ondersteuningsteam heeft gereageerd op uw live chat bericht.');
add('latest_reply','Latest Reply','Última Respuesta','Dernière Réponse','Neueste Antwort','Última Resposta','Ultima Risposta','最新回复','最新の返信','최신 답변','آخر رد','नवीनतम जवाब','Последний ответ','Son Yanıt','Phản hồi Mới nhất','Laatste reactie');
add('view_reply_continue','View Reply & Continue Chat','Ver Respuesta y Continuar Chat','Voir la Réponse et Continuer le Chat','Antwort Ansehen & Chat Fortsetzen','Ver Resposta e Continuar Chat','Visualizza Risposta e Continua Chat','查看回复并继续聊天','返信を表示してチャットを続ける','답변 보기 및 채팅 계속','عرض الرد ومتابعة الدردشة','जवाब देखें और चैट जारी रखें','Просмотреть ответ и продолжить чат','Yanıtı Görüntüle ve Sohbete Devam Et','Xem Phản hồi và Tiếp tục Trò chuyện','Bekijk reactie & ga door met chatten');
add('need_help','Need help?','¿Necesita ayuda?','Besoin d\'aide?','Brauchen Sie Hilfe?','Precisa de ajuda?','Hai bisogno di aiuto?','需要帮助？','ヘルプが必要ですか？','도움이 필요하신가요؟','هل تحتاج إلى مساعدة؟','क्या आपको मदद चाहिए?','Нужна помощь?','Yardıma mı ihtiyacınız var?','Cần trợ giúp?','Hulp nodig?');
add('continue_live_chat','Continue live chat','Continuar chat en vivo','Continuer le chat en direct','Live-Chat fortsetzen','Continuar chat ao vivo','Continua chat dal vivo','继续实时聊天','ライブチャットを続ける','라이브 채팅 계속','متابعة الدردشة المباشرة','लाइव चैट जारी रखें','Продолжить чат','Canlı sohbete devam et','Tiếp tục trò chuyện trực tiếp','Ga door met live chat');
add('button_doesnt_work',"If the button doesn't work, copy and paste this link:","Si el botón no funciona, copie y pegue este enlace:","Si le bouton ne fonctionne pas, copiez et collez ce lien:","Wenn die Schaltfläche nicht funktioniert, kopieren und fügen Sie diesen Link ein:","Se o botão não funcionar, copie e cole este link:","Se il pulsante non funziona, copia e incolla questo link:","如果按钮不起作用，请复制并粘贴此链接：","ボタンが機能しない場合は、このリンクをコピーして貼り付けてください。","버튼이 작동하지 않으면 이 링크를 복사하여 붙여넣으십시오.","إذا لم يعمل الزر، يرجى نسخ هذا الرابط ولصقه:","यदि बटन काम नहीं करता है, तो इस लिंक को कॉपी और पेस्ट करें:","Если кнопка не работает, скопируйте и вставьте эту ссылку:","Buton çalışmazsa bu bağlantıyı kopyalayıp yapıştırın:","Nếu nút không hoạt động, hãy sao chép và dán liên kết này:","Als de knop niet werkt, kopieer en plak dan deze link:");
add('hello_there','Hello','Hola','Bonjour','Hallo','Olá','Ciao','您好','こんにちは','안녕하세요','مرحباً','नमस्ते','Здравствуйте','Merhaba','Xin chào','Hallo');

// --- Bank-specific labels ---
add('amount','Amount','Monto','Montant','Betrag','Valor','Importo','金额','金額','금액','المبلغ','राशि','Сумма','Tutar','Số tiền','Bedrag');
add('fee','Fee','Tarifa','Frais','Gebühr','Taxa','Commissione','费用','手数料','수수료','الرسوم','शुल्क','Комиссия','Ücret','Phí','Kosten');
add('total','Total','Total','Total','Gesamt','Total','Totale','总计','合計','총계','الإجمالي','कुल','Итого','Toplam','Tổng cộng','Totaal');
add('subtotal','Subtotal','Subtotal','Sous-total','Zwischensumme','Subtotal','Subtotale','小计','小計','소계','المجموع الفرعي','उपयोग','Промежуточный итог','Ara toplam','Tạm tính','Subtotaal');
add('transaction_id','Transaction ID','ID de Transacción','ID de Transaction','Transaktions-ID','ID da Transação','ID Transazione','交易编号','取引ID','거래 ID','معرف المعاملة','लेनदेन आईडी','Идентификатор транзакции','İşlem Kimliği','Mã Giao dịch','Transactie ID');
add('transaction_date','Transaction date','Fecha de transacción','Date de transaction','Transaktionsdatum','Data da transação','Data transazione','交易日期','取引日付','거래 날짜','تاريخ المعاملة','लेनदेन तिथि','Дата транзакции','İşlem Tarihi','Ngày giao dịch','Transactiedatum');
add('sender','Sender','Remitente','Expéditeur','Absender','Remetente','Mittente','发送人','送信者','발신인','المرسل','प्रेषक','Отправитель','Gönderen','Người gửi','Afzender');
add('sender_name','Sender Name','Nombre del Remitente','Nom de l\'expéditeur','Name des Absenders','Nome do Remetente','Nome del Mittente','发送人姓名','送信者名','발신인 이름','اسم المرسل','प्रेषक का नाम','Имя отправителя','Gönderen Adı','Tên người gửi','Naam afzender');
add('recipient_name','Recipient Name','Nombre del Destinatario','Nom du destinataire','Name des Empfängers','Nome do Destinatário','Nome del Destinatario','收款人姓名','受取人名','수신인 이름','اسم المستلم','प्राप्तकर्ता का नाम','Имя получателя','Alıcı Adı','Tên người nhận','Naam ontvanger');
add('recipient_email','Recipient Email','Correo del Destinatario','Email du destinataire','E-Mail des Empfängers','Email do Destinatário','Email del Destinatario','收款人邮箱','受取人メール','수신인 이메일','بريد المستلم','प्राप्तकर्ता ईमेल','Email получателя','Alıcı E-postası','Email người nhận','Email ontvanger');
add('recipient_account','Recipient Account','Cuenta del Destinatario','Compte du destinataire','Empfängerkonto','Conta do Destinatário','Conto del Destinatario','收款人账户','受取人口座','수신인 계정','حساب المستلم','प्राप्तकर्ता खाता','Счет получателя','Alıcı Hesabı','Tài khoản người nhận','Rekening ontvanger');

// --- Titles & Salutations ---
add('incoming_deposit_notification','Incoming Direct Deposit Notification','Notificación de Depósito Directo Entrante','Notification de Dépôt Direct Entrant','Eingehende Direkteinzahlungsbenachrichtigung','Notificação de Depósito Direto Recebido','Notifica di Deposito Diretto in Entrata',' incoming 直接存款通知','着金直接預金通知','입금 알림','إشعار الإيداع المباشر الوارد','आने वाला सीधा जमा अधिसूचना','Уведомление о входящем прямом депозите','Gelen Doğrudan Mevduat Bildirimi','Thông báo Gửi tiền Trực tiếp Đến','Melding Binnenkomende Storting');
add('direct_deposit_confirmation','Direct Deposit Confirmation','Confirmación de Depósito Directo','Confirmation de Dépôt Direct','Bestätigung der Direkteinzahlung','Confirmação de Depósito Direto','Conferma di Deposito Diretto','直接存款确认','直接預金の確認','직접 입금 확인','تأكيد الإيداع المباشر','सीधा जमा पुष्टि','Подтверждение прямого депозита','Doğrudan Mevduat Onayı','Xác nhận Gửi tiền Trực tiếp','Bevestiging Directe Storting');
add('dear','Dear','Estimado','Cher','Sehr geehrte/r','Prezado','Gentile','尊敬的','拝啓','존경하는','عزيزي','प्रिय','Уважаемый','Sayın','Kính gửi','Geachte');
add('hi','Hi','Hola','Bonjour','Hallo','Olá','Ciao','你好','こんにちは','안녕하세요','مرحباً','नमस्ते','Привет','Merhaba','Xin chào','Hoi');
add('valued_customer','Valued Customer','Cliente Valioso','Client Privilégié','Geschätzter Kunde','Cliente Valioso','Cliente di Valore','尊贵客户','大切なお客様','소중한 고객','عميل مهم','मूल्यवान ग्राहक','Уважаемый клиент','Değerli Müşteri','Khách hàng Quý giá','Geachte klant');
add('deposit_intro','We are writing to inform you that a direct deposit has been received and credited to your account. Please review the transaction details below.','Le informamos que se ha recibido y acreditado un depósito directo en su cuenta. Revise los detalles a continuación.','Nous vous informons qu\'un dépôt direct a été reçu et crédité sur votre compte. Veuillez consulter les détails ci-dessous.','Wir informieren Sie, dass eine Direkteinzahlung eingegangen und auf Ihrem Konto gutgeschrieben wurde. Bitte überprüfen Sie die Details unten.','Informamos que um depósito direto foi recebido e creditado em sua conta. Por favor, revise os detalhes abaixo.','Le scriviamo per informarla che un deposito diretto è stato ricevuto e accreditato sul suo conto. Si prega di rivedere i dettagli qui sotto.','我们写信通知您，一笔直接存款已收到并存入您的账户。请查看以下详情。','直接預金が受け取られ、ご口座に入金されたことをお知らせします。以下の詳細をご確認ください。','귀하의 계좌로 직접 입금이 접수되어 입금되었습니다. 아래 내역을 확인해 주세요.','نكتب لإبلاغك بأنه تم استلام إيداع مباشر وإضافته إلى حسابك. يرجى مراجعة التفاصيل أدناه.','हम आपको सूचित करने के लिए लिख रहे हैं कि एक सीधा जमा प्राप्त हो गया है और आपके खाते में जमा किया गया है। कृपया नीचे विवरण की समीक्षा करें।','Мы пишем, чтобы сообщить вам, что прямой депозит был получен и зачислен на ваш счет. Пожалуйста, ознакомьтесь с деталями ниже.','Hesabınıza bir doğrudan mevduatın alındığını ve yatırıldığını bildirmek için yazıyoruz. Lütfen aşağıdaki detayları inceleyin.','Chúng tôi viết thư để thông báo rằng một khoản gửi trực tiếp đã được nhận và ghi có vào tài khoản của bạn. Vui lòng xem xét chi tiết bên dưới.','We schrijven u om u te informeren dat een directe storting is ontvangen en op uw rekening is bijgeschreven. Bekijk de details hieronder.');
add('deposit_intro_peoplechoice','We are pleased to inform you that a direct deposit has been credited to your account. No further action is required unless you notice any discrepancies.','Nos complace informarle que un depósito directo ha sido acreditado en su cuenta. No se requiere acción adicional a menos que note alguna discrepancia.','Nous avons le plaisir de vous informer qu\'un dépôt direct a été crédité sur votre compte. Aucune action supplémentaire n\'est requise sauf si vous remarquez des divergences.','Wir freuen uns, Ihnen mitteilen zu dürfen, dass eine Direkteinzahlung auf Ihrem Konto gutgeschrieben wurde. Es sind keine weiteren Maßnahmen erforderlich, es sei denn, Ihnen fallen Unstimmigkeiten auf.','Temos o prazer de informar que um depósito direto foi creditado em sua conta. Nenhuma ação adicional é necessária, a menos que você note alguma discrepância.','Siamo lieti di informarla che un deposito diretto è stato accreditato sul suo conto. Non è necessaria alcuna ulteriore azione a meno che non noti discrepanze.','我们很高兴通知您，一笔直接存款已存入您的账户。除非您发现任何差异，否则无需进一步操作。','直接預金がご口座に入金されたことをお知らせします。不審な点がない限り、追加の対応は不要です。','귀하의 계좌로 직접 입금이 처리되었습니다. 이상이 없으면 추가 조치가 필요하지 않습니다.','يسعدنا إبلاغك بأنه تم إضافة إيداع مباشر إلى حسابك. لا يلزم اتخاذ أي إجراء إضافي ما لم تلاحظ أي تناقضات.','हमें यह सूचित करते हुए प्रसन्नता हो रही है कि एक सीधा जमा आपके खाते में जमा किया गया है। जब तक आपको कोई असंगति नहीं दिखती, तब तक कोई further action की आवश्यकता नहीं है।','Мы рады сообщить вам, что прямой депозит был зачислен на ваш счет. Никаких дополнительных действий не требуется, если вы не заметите каких-либо расхождений.','Hesabınıza bir doğrudan mevduatın yatırıldığını bildirmekten memnuniyet duyuyoruz. Herhangi bir tutarsızlık fark etmediğiniz sürece başka bir işlem gerekmez.','Chúng tôi vui mừng thông báo rằng một khoản gửi trực tiếp đã được ghi có vào tài khoản của bạn. Không cần hành động nào khác trừ khi bạn nhận thấy bất kỳ sự khác biệt nào.','We zijn verheugd u te informeren dat een directe storting op uw rekening is bijgeschreven. Er is geen verdere actie nodig, tenzij u discrepanties opmerkt.');

add('transaction_details','Transaction Details','Detalles de la Transacción','Détails de la Transaction','Transaktionsdetails','Detalhes da Transação','Dettagli della Transazione','交易详情','取引詳細','거래 내역','تفاصيل المعاملة','लेनदेन विवरण','Детали транзакции','İşlem Detayları','Chi tiết Giao dịch','Transactiedetails');
add('action_required','Action Required','Acción Requerida','Action Requise','Aktion Erforderlich','Ação Necessária','Azione Richiesta','需要操作','対応が必要です','조치 필요','إجراء مطلوب','कार्रवाई आवश्यक','Требуется действие','Eylem Gerekli','Yêu cầu Hành động','Actie vereist');
add('confirm_receipt_deposit','Please confirm the receipt of this deposit to complete the transaction record.','Por favor, confirme la recepción de este depósito para completar el registro.','Veuillez confirmer la réception de ce dépôt pour compléter l\'enregistrement.','Bitte bestätigen Sie den Erhalt dieser Einzahlung, um den Datensatz zu vervollständigen.','Por favor, confirme o recebimento deste depósito para completar o registro.','Si prega di confermare la ricezione di questo deposito per completare la registrazione.','请确认收到此存款以完成交易记录。','この入金の受取を確認して、取引記録を完了してください。','거래 기록을 완료하려면 이 입금의 수령을 확인해 주세요.','يرجى تأكيد استلام هذا الإيداع لإكمال سجل المعاملة.','कृपया लेनदेन रिकॉर्ड पूरा करने के लिए इस जमा की प्राप्ति की पुष्टि करें।','Пожалуйста, подтвердите получение этого депозита для завершения записи транзакции.','Lütfen işlem kaydını tamamlamak için bu mevduatın alındığını onaylayın.','Vui lòng xác nhận đã nhận khoản tiền gửi này để hoàn tất hồ sơ giao dịch.','Bevestig de ontvangst van deze storting om het transactieoverzicht te voltooien.');
add('confirm_payment','Confirm Payment','Confirmar Pago','Confirmer le Paiement','Zahlung Bestätigen','Confirmar Pagamento','Conferma Pagamento','确认付款','支払いを確認','결제 확인','تأكيد الدفع','भुगतान की पुष्टि करें','Подтвердить платеж','Ödemeyi Onayla','Xác nhận Thanh toán','Bevestig betaling');
add('confirm_deposit','Confirm Deposit','Confirmar Depósito','Confirmer le Dépôt','Einzahlung Bestätigen','Confirmar Depósito','Conferma Deposito','确认存款','預金を確認','입금 확인','تأكيد الإيداع','जमा की पुष्टि करें','Подтвердить депозит','Mevduatı Onayla','Xác nhận Tiền gửi','Bevestig storting');
add('security_notice','Security Notice','Aviso de Seguridad','Avis de Sécurité','Sicherheitshinweis','Aviso de Segurança','Avviso di Sicurezza','安全提示','セキュリティ通知','보안 알림','إشعار الأمان','सुरक्षा सूचना','Уведомление безопасности','Güvenlik Uyarısı','Thông báo Bảo mật','Beveiligingsmelding');
add('security_notice_text','{bank} will never ask you for your password, PIN, or full card number via email. If you did not expect this deposit, please contact our Fraud Prevention team immediately through the support chat.','{bank} nunca le pedirá su contraseña, PIN o número de tarjeta completo por correo electrónico. Si no esperaba este depósito, comuníquese inmediatamente con nuestro equipo de Prevención de Fraude.','{bank} ne vous demandera jamais votre mot de passe, votre code PIN ou votre numéro de carte complet par e-mail. Si vous n\'attendiez pas ce dépôt, veuillez contacter immédiatement notre équipe de Prévention de la Fraude.','{bank} wird Sie niemals per E-Mail nach Ihrem Passwort, PIN oder Ihrer vollständigen Kartennummer fragen. Wenn Sie diese Einzahlung nicht erwartet haben, kontaktieren Sie bitte sofort unser Fraud Prevention-Team.','{bank} nunca solicitará sua senha, PIN ou número completo do cartão por e-mail. Se você não esperava este depósito, entre em contato imediatamente com nossa equipe de Prevenção de Fraudes.','{bank} non ti chiederà mai la password, il PIN o il numero completo della carta via e-mail. Se non ti aspettavi questo deposito, contatta immediatamente il nostro team di Prevenzione delle Frodi.','{bank}绝不会通过电子邮件向您索取密码、PIN码或完整的卡号。如果您没有预料到此笔存款，请立即联系我们的欺诈预防团队。','{bank}はメールでパスワード、PIN、またはカード番号全体を尋ねることはありません。この入金を予期していない場合は、不正防止チームにすぐにご連絡ください。','{bank}은(는) 이메일로 비밀번호, PIN 또는 전체 카드 번호를 절대 요청하지 않습니다. 이 입금을 예상하지 못했다면 지원 채팅을 통해 사기 방지팀에 즉시 문의하십시오.','لن يطلب منك {bank} أبدًا كلمة المرور أو رقم التعريف الشخصي أو رقم البطاقة الكامل عبر البريد الإلكتروني. إذا لم تكن تتوقع هذا الإيداع، يرجى الاتصال بفريق منع الاحتيال على الفور.','{bank} आपसे कभी भी ईमेल के माध्यम से आपका पासवर्ड, PIN या पूर्ण कार्ड नंबर नहीं मांगेगा। यदि आपने यह जमा अपेक्षित नहीं किया था, तो कृपया सहायता चैट के माध्यम से तुरंत हमारी धोखाधड़ी रोकथाम टीम से संपर्क करें।','{bank} никогда не попросит у вас пароль, PIN-код или полный номер карты по электронной почте. Если вы не ожидали этот депозит, немедленно свяжитесь с нашей командой по предотвращению мошенничества.','{bank} size asla e-posta yoluyla şifrenizi, PIN\'inizi veya tam kart numaranızı sormayacaktır. Bu mevduatı beklemiyorsanız, lütfen destek sohbeti aracılığıyla Dolandırıcılık Önleme ekibimizle hemen iletişime geçin.','{bank} sẽ không bao giờ yêu cầu bạn cung cấp mật khẩu, PIN hoặc số thẻ đầy đủ qua email. Nếu bạn không mong đợi khoản tiền gửi này, vui lòng liên hệ ngay với nhóm Phòng chống Gian lận.','{bank} zal u nooit vragen om uw wachtwoord, PIN of volledige kaartnummer via e-mail. Als u deze storting niet verwachtte, neem dan onmiddellijk contact op met ons Fraud Prevention-team.');
add('automated_notification','This is an automated notification from {bank}. Please do not reply to this email.','Esta es una notificación automatizada de {bank}. Por favor, no responda a este correo.','Ceci est une notification automatique de {bank}. Veuillez ne pas répondre à cet e-mail.','Dies ist eine automatische Benachrichtigung von {bank}. Bitte antworten Sie nicht auf diese E-Mail.','Esta é uma notificação automatizada do {bank}. Por favor, não responda a este e-mail.','Questa è una notifica automatica da {bank}. Si prega di non rispondere a questa e-mail.','这是来自{bank}的自动通知。请勿回复此邮件。','これは{bank}からの自動通知です。このメールに返信しないでください。','이것은 {bank}의 자동 알림입니다. 이 이메일에 회신하지 마십시오.','هذا إشعار تلقائي من {bank}. يرجى عدم الرد على هذا البريد الإلكتروني.','यह {bank} से एक स्वचालित अधिसूचना है। कृपया इस ईमेल का जवाब न दें।','Это автоматическое уведомление от {bank}. Пожалуйста, не отвечайте на это письмо.','Bu, {bank} tarafından gönderilen otomatik bir bildirimdir. Lütfen bu e-postaya yanıt vermeyin.','Đây là thông báo tự động từ {bank}. Vui lòng không trả lời email này.','Dit is een automatische melding van {bank}. Reageer alstublieft niet op deze e-mail.');
add('all_rights_reserved','All rights reserved','Todos los derechos reservados','Tous droits réservés','Alle Rechte vorbehalten','Todos os direitos reservados','Tutti i diritti riservati','版权所有','全著作権所有','모든 권리 보유','جميع الحقوق محفوظة','सर्वाधिकार सुरक्षित','Все права защищены','Tüm hakları saklıdır','Đã đăng ký Bản quyền','Alle rechten voorbehouden');
add('member_fdic','Member FDIC','Miembro FDIC','Membre FDIC','Mitglied FDIC','Membro FDIC','Membro FDIC','FDIC成员','FDIC加盟','FDIC 회원','عضو FDIC','FDIC सदस्य','Член FDIC','FDIC Üyesi','Thành viên FDIC','Lid FDIC');
add('equal_housing_lender','Equal Housing Lender','Prestador de Vivienda Igualitaria','Prêteur Logement Équitable','Gleichberechtigter Hypothekengeber','Credor de Habitação Igualitária','Prestatore di Mutui Abitativi Equo','平等住房贷款机构','平等住宅貸付機関','동일 주택 대출 기관','مقرض السكن المتساوي','समान आवास ऋणदाता','Равноправный Ипотечный Кредитор','Eşit Konut Kredisi Veren Kuruluş','Nhà Cho Vay Nhà Ở Bình đẳng','Gelijke Huisvesting Kredietverstrekker');
add('member_kdic','Member KDIC','Miembro KDIC','Membre KDIC','Mitglied KDIC','Membro KDIC','Membro KDIC','KDIC成员','KDIC加盟','KDIC 회원','عضو KDIC','KDIC सदस्य','Член KDIC','KDIC Üyesi','Thành viên KDIC','Lid KDIC');
add('time','Time','Hora','Heure','Zeit','Hora','Ora','时间','時間','시간','الوقت','समय','Время','Zaman','Thời gian','Tijd');
add('confirm_accept_deposit','Confirm & Accept Deposit','Confirmar y Aceptar Depósito','Confirmer et Accepter le Dépôt','Einzahlung Bestätigen und Akzeptieren','Confirmar e Aceitar Depósito','Conferma e Accetta Deposito','确认并接受存款','入金を確認して受け入れる','입금 확인 및 수락','تأكيد وقبول الإيداع','जमा की पुष्टि करें और स्वीकार करें','Подтвердить и принять депозит','Mevduatı Onayla ve Kabul Et','Xác nhận và Chấp nhận Tiền gửi','Bevestig en Accepteer Storting');
add('track_transfers_anytime','Track transfers anytime at','Rastree transferencias en cualquier momento en','Suivez les transferts à tout moment sur','Überweisungen jederzeit verfolgen unter','Rastreie transferências a qualquer momento em','Traccia i trasferimenti in qualsiasi momento su','随时追踪转账','いつでも送金を追跡','언제든지 송금 추적','تتبع التحويلات في أي وقت على','कभी भी स्थानांतरण ट्रैक करें','Отслеживайте переводы в любое время на','Transferleri istediğiniz zaman takip edin','Theo dõi chuyển khoản mọi lúc tại','Volg overboekingen altijd op via');
add('thank_you_for_using','Thank you for using','Gracias por usar','Merci d\'utiliser','Danke, dass Sie','Obrigado por usar','Grazie per aver utilizzato','感谢您使用','ご利用ありがとうございます','사용해 주셔서 감사합니다','شكراً لاستخدامك','उपयोग करने के लिए धन्यवाद','Спасибо за использование','Kullandığınız için teşekkür ederiz','Cảm ơn bạn đã sử dụng','Bedankt voor het gebruik van');
add('international_money_transfer_receipt','International Money Transfer Receipt','Recibo de Transferencia Internacional de Dinero','Reçu de Transfert d\'Argent International','Quittung für internationale Geldüberweisung','Recibo de Transferência Internacional de Dinheiro','Ricevuta di Trasferimento di Denaro Internazionale','国际汇款收据','国際送金領収書','국제 송금 영수증','إيصال التحويل المالي الدولي','अंतर्राष्ट्रीय धन हस्तांतरण रसीद','Квитанция международного денежного перевода','Uluslararası Para Transferi Makbuzu','Biên lai Chuyển tiền Quốc tế','Ontvangstbewijs Internationale Geldoverdracht');
add('fast_transparent_low_fees','Fast, Transparent, Low Fees.','Rápido, Transparente, Bajas Tarifas.','Rapide, Transparent, Faibles Frais.','Schnell, Transparent, Niedrige Gebühren.','Rápido, Transparente, Taxas Baixas.','Veloce, Trasparente, Commissioni Basse.','快速、透明、低费用。','迅速、透明、低料金。','빠르고, 투명하고, 저렴한 수수료.','سريع، شفاف، رسوم منخفضة.','तेज़, पारदर्शी, कम शुल्क।','Быстро, Прозрачно, Низкие Комиссии.','Hızlı, Şeffaf, Düşük Ücretler.','Nhanh chóng, Minh bạch, Phí Thấp.','Snel, Transparant, Lage Kosten.');
add('we_sent_money','We sent money to','Enviamos dinero a','Nous avons envoyé de l\'argent à','Wir haben Geld gesendet an','Enviamos dinheiro para','Abbiamo inviato denaro a','我们汇款给','送金先','송금 대상','أرسلنا الأموال إلى','हमने पैसे भेजे','Мы отправили деньги','Para gönderdik','Chúng tôi đã gửi tiền đến','We hebben geld gestuurd naar');
add('sent_you','sent you','le envió','vous a envoyé','hat Ihnen gesendet','enviou-lhe','ti ha inviato','发送给您','が送金しました','님에게 보냈습니다','أرسل لك','ने आपको भेजा','отправил вам','size gönderdi','đã gửi cho bạn','heeft u gestuurd');
add('business_address','Business Address','Dirección Comercial','Adresse Professionnelle','Geschäftsadresse','Endereço Comercial','Indirizzo Commerciale','公司地址','事業所住所','사업장 주소','عنوان العمل','व्यवसायिक पता','Юридический Адрес','İş Adresi','Địa chỉ Doanh nghiệp','Zakelijk Adres');
add('dont_see_money',"Don't see the money in your account?",'¿No ve el dinero en su cuenta?','Vous ne voyez pas l\'argent sur votre compte?','Sie sehen das Geld nicht auf Ihrem Konto?','Não vê o dinheiro na sua conta?','Non vedi i soldi sul tuo conto?','没有在账户中看到资金？','口座に入金が反映されていませんか？','계좌에 돈이 보이지 않나요؟','لا ترى الأموال في حسابك؟','क्या आपको अपने खाते में पैसा नहीं दिख रहा है?','Не видите деньги на своем счете?','Hesabınızda parayı göremiyor musunuz?','Không thấy tiền trong tài khoản của bạn?','Ziet u het geld niet op uw rekening?');
add('dont_worry_show_up',"Don't worry — it may take a few moments to show up.",'No se preocupe: puede tardar unos momentos en aparecer.','Ne vous inquiétez pas : cela peut prendre quelques instants pour apparaître.','Keine Sorge — es kann einen Moment dauern, bis es angezeigt wird.','Não se preocupe — pode levar alguns momentos para aparecer.','Non preoccuparti: potrebbe volerci qualche istante per apparire.','不用担心——可能需要几分钟才会显示。','ご心配なく——反映されるまでに数分かかる場合があります。','걱정하지 마세요——잠시 후에 표시될 수 있습니다.','لا تقلق — قد يستغرق الأمر لحظات حتى يظهر.','चिंता न करें — इसे दिखने में कुछ क्षण लग सकते हैं।','Не волнуйтесь — это может занять несколько мгновений.','Endişelenmeyin — görünmesi birkaç dakika sürebilir.','Đừng lo lắng — có thể mất vài phút để hiển thị.','Maak u geen zorgen — het kan even duren voordat het verschijnt.');
add('paypal_payment_received','PayPal Payment Received','Pago de PayPal Recibido','Paiement PayPal Reçu','PayPal-Zahlung Erhalten','Pagamento do PayPal Recebido','Pagamento PayPal Ricevuto','已收到PayPal付款','PayPal支払いを受け取りました','PayPal 결제 수신','تم استلام دفع PayPal','PayPal भुगतान प्राप्त हुआ','Получен платеж PayPal','PayPal Ödemesi Alındı','Đã Nhận Thanh toán PayPal','PayPal-betaling Ontvangen');
add('paypal_payment_failed','PayPal Payment Failed','Pago de PayPal Fallido','Paiement PayPal Échoué','PayPal-Zahlung Fehlgeschlagen','Pagamento do PayPal Falhou','Pagamento PayPal Fallito','PayPal付款失败','PayPal支払いに失敗しました','PayPal 결제 실패','فشل دفع PayPal','PayPal भुगतान विफल','Ошибка платежа PayPal','PayPal Ödemesi Başarısız','Thanh toán PayPal Thất bại','PayPal-betaling Mislukt');
add('verify_your_identity','Verify Your Identity','Verifique Su Identidad','Vérifiez Votre Identité','Überprüfen Sie Ihre Identität','Verifique Sua Identidade','Verifica la Tua Identità','验证您的身份','ご本人確認','본인 인증','تحقق من هويتك','अपनी पहचान सत्यापित करें','Подтвердите свою личность','Kimliğinizi Doğrulayın','Xác minh Danh tính của Bạn','Verifieer uw identiteit');
add('use_code_below','Use the code below to verify your identity.','Use el código a continuación para verificar su identidad.','Utilisez le code ci-dessous pour vérifier votre identité.','Verwenden Sie den unten stehenden Code, um Ihre Identität zu überprüfen.','Use o código abaixo para verificar sua identidade.','Utilizza il codice qui sotto per verificare la tua identità.','使用下方代码验证您的身份。','以下のコードを使用してご本人確認を行ってください。','아래 코드를 사용하여 본인 인증을 완료하세요.','استخدم الرمز أدناه للتحقق من هويتك.','अपनी पहचान सत्यापित करने के लिए नीचे दिए गए कोड का उपयोग करें।','Используйте код ниже для подтверждения личности.','Kimliğinizi doğrulamak için aşağıdaki kodu kullanın.','Sử dụng mã bên dưới để xác minh danh tính của bạn.','Gebruik de onderstaande code om uw identiteit te verifiëren.');
add('code_expire_10min','This code will expire in 10 minutes.','Este código expirará en 10 minutos.','Ce code expirera dans 10 minutes.','Dieser Code läuft in 10 Minuten ab.','Este código expirará em 10 minutos.','Questo codice scadrà tra 10 minuti.','此代码将在10分钟后过期。','このコードは10分後に失効します。','이 코드는 10분 후에 만료됩니다.','هذا الرمز سينتهي خلال 10 دقائق.','यह कोड 10 मिनट में समाप्त हो जाएगा।','Этот код истечет через 10 минут.','Bu kod 10 dakika içinde sona erecek.','Mã này sẽ hết hạn sau 10 phút.','Deze code verloopt over 10 minuten.');
add('if_didnt_request_ignore','If you did not request this code, please ignore this email.','Si no solicitó este código, ignore este correo.','Si vous n\'avez pas demandé ce code, veuillez ignorer cet e-mail.','Wenn Sie diesen Code nicht angefordert haben, ignorieren Sie bitte diese E-Mail.','Se você não solicitou este código, ignore este e-mail.','Se non hai richiesto questo codice, ignora questa e-mail.','如果您没有请求此代码，请忽略此邮件。','このコードをリクエストしていない場合は、このメールを無視してください。','이 코드를 요청하지 않으셨다면 이 이메일을 무시하십시오.','إذا لم تطلب هذا الرمز، يرجى تجاهل هذا البريد الإلكتروني.','यदि आपने यह कोड अनुरोध नहीं किया है, तो कृपया इस ईमेल को अनदेखा करें।','Если вы не запрашивали этот код, проигнорируйте это письмо.','Bu kodu talep etmediyseniz, lütfen bu e-postayı dikkate almayın.','Nếu bạn không yêu cầu mã này, vui lòng bỏ qua email này.','Als u deze code niet heeft aangevraagd, negeer dan deze e-mail.');
add('welcome_future_banking','Welcome to the Future of Banking','Bienvenido al Futuro de la Banca','Bienvenue dans le Futur de la Banque','Willkommen in der Zukunft des Bankwesens','Bem-vindo ao Futuro da Banca','Benvenuto nel Futuro della Banca','欢迎进入银行新时代','銀行の未来へようこそ','은행의 미래에 오신 것을 환영합니다','مرحباً بك في مستقبل المصرفية','बैंकिंग के भविष्य में आपका स्वागत है','Добро пожаловать в Будущее Банкинга','Bankacılığın Geleceğine Hoş Geldiniz','Chào mừng đến với Tương lai của Ngân hàng','Welkom bij de Toekomst van Bankieren');
add('account_activated','Your account has been successfully activated!','¡Su cuenta ha sido activada exitosamente!','Votre compte a été activé avec succès !','Ihr Konto wurde erfolgreich aktiviert!','Sua conta foi ativada com sucesso!','Il tuo conto è stato attivato con successo!','您的账户已成功激活！','アカウントが正常に有効化されました！','계정이 성공적으로 활성화되었습니다!','تم تفعيل حسابك بنجاح!','आपका खाता सफलतापूर्वक सक्रिय हो गया है!','Ваш аккаунт успешно активирован!','Hesabınız başarıyla etkinleştirildi!','Tài khoản của bạn đã được kích hoạt thành công!','Uw account is succesvol geactiveerd!');
add('instant_global_transfers','Instant Global Transfers','Transferencias Globales Instantáneas','Transferts Mondiaux Instantanés','Sofortige globale Überweisungen','Transferências Globais Instantâneas','Trasferimenti Globali Istantanei','即时全球转账','即時グローバル送金','즉시 글로벌 송금','تحويلات عالمية فورية','तुरंत वैश्विक स्थानांतरण','Мгновенные международные переводы','Anında Küresel Transferler','Chuyển tiền Toàn cầu Tức thì','Directe Wereldwijze Overboekingen');
add('crypto_high_yield','Crypto & High-Yield Accounts','Cuentas de Cripto y Alto Rendimiento','Comptes Crypto et Haut Rendement','Krypto- und Hochzinskonten','Contas de Cripto e Alto Rendimento','Conti Crypto e Alto Rendimento','加密货币与高收益账户','暗号資産・高利回り口座','암호화폐 및 고수익 계정','حسابات العملات المشفرة والعائد المرتفع','क्रिप्टो और उच्च-पैदावार खाते','Крипто и высокодоходные счета','Kripto ve Yüksek Getirili Hesaplar','Tài khoản Tiền điện tử & Lợi nhuận Cao','Crypto & Hoge Opbrengstrekeningen');
add('ai_finance_insights','AI Finance Insights','Información Financiera con IA','Informations Financières par IA','KI-Finanzanalysen','Informações Financeiras com IA','Approfondimenti Finanziari con IA','人工智能金融洞察','AIファイナンス洞察','AI 금융 인사이트','رؤى التمويل بالذكاء الاصطناعي','AI वित्त अंतर्दृष्टि','Финансовая аналитика ИИ','AI Finans Analizleri','Thông tin Tài chính AI','AI Financiële Inzichten');
add('dedicated_support','24/7 Dedicated Support','Soporte Dedicado 24/7','Support Dédié 24h/24 et 7j/7','Rund um die Uhr dedizierter Support','Suporte Dedicado 24/7','Supporto Dedicato 24/7','24/7专属客服','24時間年中無休の専用サポート','24/7 전담 지원','دعم مخصص على مدار الساعة','24/7 समर्पित सहायता','Круглосуточная поддержка','7/24 Özel Destek','Hỗ trợ Chuyên dụng 24/7','24/7 Toegewijde Ondersteuning');
add('new_signin_detected','New Sign-In Detected','Nuevo Inicio de Sesión Detectado','Nouvelle Connexion Détectée','Neue Anmeldung Erkannt','Novo Login Detectado','Nuovo Accesso Rilevato','检测到新登录','新しいサインインが検出されました','새로운 로그인 감지됨','تم الكشف عن تسجيل دخول جديد','नया साइन-इन पहचाना गया','Обнаружен новый вход','Yeni Oturum Açma Algılandı','Phát hiện Đăng nhập Mới','Nieuwe Aanmelding Gedetecteerd');
add('noticed_new_login','We noticed a new login to your account. If this was you, you can safely ignore this alert.','Notamos un nuevo inicio de sesión en su cuenta. Si fue usted, puede ignorar esta alerta de forma segura.','Nous avons remarqué une nouvelle connexion à votre compte. Si c\'était vous, vous pouvez ignorer cette alerte en toute sécurité.','Wir haben eine neue Anmeldung bei Ihrem Konto festgestellt. Wenn Sie das waren, können Sie diese Warnung bedenkenlos ignorieren.','Notamos um novo login na sua conta. Se foi você, pode ignorar este alerta com segurança.','Abbiamo notato un nuovo accesso al tuo conto. Se sei stato tu, puoi ignorare questo avviso in tutta sicurezza.','我们检测到您账户的新登录。如果是您本人操作，请放心忽略此提醒。','アカウントへの新しいログインを検出しました。ご本人の場合は、この警告を無視して構いません。','귀하의 계정에서 새로운 로그인이 감지되었습니다. 본인이시라면 이 알림을 안전하게 무시하셔도 됩니다.','لاحظنا تسجيل دخول جديد إلى حسابك. إذا كنت أنت، يمكنك تجاهل هذا التنبيه بأمان.','हमने आपके खाते में एक नया लॉगिन देखा। यदि यह आप थे, तो आप इस अलर्ट को सुरक्षित रूप से अनदेखा कर सकते हैं।','Мы заметили новый вход в ваш аккаунт. Если это были вы, можете спокойно проигнорировать это предупреждение.','Hesabınıza yeni bir giriş yapıldığını fark ettik. Bu sizseniz, bu uyarıyı güvenle görmezden gelebilirsiniz.','Chúng tôi nhận thấy một lần đăng nhập mới vào tài khoản của bạn. Nếu đó là bạn, bạn có thể yên tâm bỏ qua cảnh báo này.','We hebben een nieuwe aanmelding bij uw account opgemerkt. Als u dit was, kunt u deze waarschuwing veilig negeren.');
add('account','Account','Cuenta','Compte','Konto','Conta','Conto','账户','アカウント','계정','الحساب','खाता','Аккаунт','Hesap','Tài khoản','Account');
add('device','Device','Dispositivo','Appareil','Gerät','Dispositivo','Dispositivo','设备','デバイス','기기','الجهاز','डिवाइस','Устройство','Cihaz','Thiết bị','Apparaat');
add('country','Country','País','Pays','Land','País','Paese','国家','国','국가','البلد','देश','Страна','Ülke','Quốc gia','Land');
add('ip_address','IP Address','Dirección IP','Adresse IP','IP-Adresse','Endereço de IP','Indirizzo IP','IP地址','IPアドレス','IP 주소','عنوان IP','IP पता','IP-адрес','IP Adresi','Địa chỉ IP','IP-adres');
add('if_not_you_secure','If this wasn\'t you, please secure your account immediately.','Si no fue usted, asegure su cuenta inmediatamente.','Si ce n\'était pas vous, veuillez sécuriser votre compte immédiatement.','Wenn Sie das nicht waren, sichern Sie bitte sofort Ihr Konto.','Se não foi você, proteja sua conta imediatamente.','Se non eri tu, proteggi immediatamente il tuo conto.','如果不是您本人操作，请立即保护您的账户。','ご本人でない場合は、直ちにアカウントを保護してください。','본인이 아니라면 즉시 계정을 보호하십시오.','إذا لم تكن أنت، يرجى تأمين حسابك على الفور.','यदि यह आप नहीं थे, तो कृपया तुरंत अपने खाते को सुरक्षित करें।','Если это были не вы, немедленно защитите свой аккаунт.','Bu siz değilseniz, lütfen hesabınızı hemen güvenli hale getirin.','Nếu không phải bạn, vui lòng bảo vệ tài khoản của bạn ngay lập tức.','Als u dit niet was, beveilig dan onmiddellijk uw account.');
add('secure_my_account','Secure My Account','Asegurar Mi Cuenta','Sécuriser Mon Compte','Mein Konto Sichern','Proteger Minha Conta','Proteggi il Mio Conto','保护我的账户','マイアカウントを保護','내 계정 보호','تأمين حسابي','मेरा खाता सुरक्षित करें','Защитить Мой Аккаунт','Hesabımı Güvenli Hale Getir','Bảo vệ Tài khoản của Tôi','Beveilig Mijn Account');
add('card_activity_alert','Card Activity Alert','Alerta de Actividad de Tarjeta','Alerte d\'Activité de Carte','Kartenaktivitätswarnung','Alerta de Atividade do Cartão','Avviso Attività Carta','卡片活动提醒','カードアクティビティアラート','카드 활동 알림','تنبيه نشاط البطاقة','कार्ड गतिविधि अलर्ट','Уведомление об Активности Карты','Kart Aktivite Uyarısı','Cảnh báo Hoạt động Thẻ','Kaartactiviteit Waarschuwing');
add('activity_on_card','We noticed activity on your card ending in {last4}.','Notamos actividad en su tarjeta que termina en {last4}.','Nous avons remarqué une activité sur votre carte se terminant par {last4}.','Wir haben Aktivitäten auf Ihrer Karte mit den Endziffern {last4} festgestellt.','Notamos atividade no seu cartão terminado em {last4}.','Abbiamo notato attività sulla tua carta che termina in {last4}.','我们检测到您尾号为{last4}的卡片有活动。','末尾が{last4}のカードでアクティビティを検出しました。','끝번호가 {last4}인 카드에서 활동이 감지되었습니다.','لاحظنا نشاطاً على بطاقتك التي تنتهي بـ {last4}.','हमने {last4} पर समाप्त होने वाले आपके कार्ड पर गतिविधि देखी।','Мы заметили активность по вашей карте, заканчивающейся на {last4}.','{last4} ile biten kartınızda hareketlilik tespit ettik.','Chúng tôi nhận thấy hoạt động trên thẻ của bạn kết thúc bằng {last4}.','We hebben activiteit op uw kaart met eindcijfers {last4} opgemerkt.');
add('action_taken','Action Taken','Acción Tomada','Action Entreprise','Ergriffene Maßnahme','Ação Tomada','Azione Intrapresa','已采取措施','実行されたアクション','취해진 조치','الإجراء المتخذ','की गई कार्रवाई','Предпринятое Действие','Alınan Eylem','Hành động Đã Thực hiện','Ondernomen Actie');
add('manage_card_settings','Manage Card Settings','Gestionar Configuración de Tarjeta','Gérer les Paramètres de la Carte','Karteneinstellungen Verwalten','Gerenciar Configurações do Cartão','Gestisci Impostazioni Carta','管理卡片设置','カード設定の管理','카드 설정 관리','إدارة إعدادات البطاقة','कार्ड सेटिंग्स प्रबंधित करें','Управление Настройками Карты','Kart Ayarlarını Yönet','Quản lý Cài đặt Thẻ','Kaartinstellingen Beheren');
add('go_to_wallet','Go to Wallet','Ir a la Billetera','Aller au Portefeuille','Zur Brieftasche Gehen','Ir para a Carteira','Vai al Portafoglio','前往钱包','ウォレットへ移動','지갑으로 이동','انتقل إلى المحفظة','वॉलेट पर जाएं','Перейти в Кошелек','Cüzdana Git','Đi đến Ví','Ga naar Portemonnee');
add('investment_account_activated','Investment Account Activated','Cuenta de Inversión Activada','Compte d\'Investissement Activé','Investmentkonto Aktiviert','Conta de Investimento Ativada','Conto di Investimento Attivato','投资账户已激活','投資口座が有効化されました','투자 계정이 활성화되었습니다','تم تفعيل حساب الاستثمار','निवेश खाता सक्रिय हो गया','Инвестиционный Счет Активирован','Yatırım Hesabı Etkinleştirildi','Tài khoản Đầu tư Đã Kích hoạt','Beleggingsrekening Geactiveerd');
add('congratulations_hy','Congratulations! You are now earning more with a High-Yield Savings Account.','¡Felicidades! Ahora está ganando más con una Cuenta de Ahorro de Alto Rendimiento.','Félicitations! Vous gagnez désormais plus avec un Compte d\'Épargne à Haut Rendement.','Herzlichen Glückwunsch! Sie verdienen jetzt mehr mit einem Hochzinskonto.','Parabéns! Agora você está ganhando mais com uma Conta Poupança de Alto Rendimento.','Congratulazioni! Ora guadagni di più con un Conto di Risparmio ad Alto Rendimento.','恭喜您！您现在已通过高收益储蓄账户赚取更多收益。','おめでとうございます！高利回り預金口座でより多くの利益を得られるようになりました。','축하합니다! 이제 고수익 저축 계좌로 더 많은 수익을 얻고 계십니다.','تهانينا! أنت الآن تربح المزيد مع حساب التوفير ذي العائد المرتفع.','बधाई हो! अब आप एक उच्च-पैदावार बचत खाते के साथ अधिक कमा रहे हैं।','Поздравляем! Теперь вы зарабатываете больше со счетом с высоким доходом.','Tebrikler! Artık Yüksek Getirili Tasarruf Hesabı ile daha fazla kazanıyorsunuz.','Xin chúc mừng! Bạn hiện đang kiếm được nhiều hơn với Tài khoản Tiết kiệm Lợi nhuận Cao.','Gefeliciteerd! U verdient nu meer met een Hoge Opbrengst Spaarrekening.');
add('current_rate','Current Rate','Tasa Actual','Taux Actuel','Aktueller Zinssatz','Taxa Atual','Tasso Attuale','当前利率','現在の金利','현재 이율','المعدل الحالي','वर्तमान दर','Текущая Ставка','Mevcut Oran','Lãi suất Hiện tại','Huidige Rente');
add('initial_locked_deposit','Initial Locked Deposit','Depósito Inicial Bloqueado','Dépôt Initial Bloqué','Anfängliche Gesperrte Einzahlung','Depósito Inicial Bloqueado','Deposito Iniziale Bloccato','初始锁定存款','初期ロック預金','초기 잠금 예금','الإيداع الأولي المقفل','प्रारंभिक लॉक्ड जमा','Начальный Заблокированный Депозит','Başlangıç Kilitli Mevduat','Tiền gửi Ban đầu Bị khóa','Initiële Geblokkeerde Storting');
add('earning_more','You are now earning more.','Ahora está ganando más.','Vous gagnez désormais plus.','Sie verdienen jetzt mehr.','Agora você está ganhando mais.','Ora guadagni di più.','您现在赚得更多了。','より多くの利益を得られるようになりました。','이제 더 많은 수익을 얻고 계십니다.','أنت الآن تربح المزيد.','अब आप अधिक कमा रहे हैं।','Теперь вы зарабатываете больше.','Artık daha fazla kazanıyorsunuz.','Bạn hiện đang kiếm được nhiều hơn.','U verdient nu meer.');
add('go_to_dashboard','Go to Dashboard','Ir al Panel','Aller au Tableau de Bord','Zum Dashboard Gehen','Ir para o Painel','Vai alla Dashboard','前往仪表盘','ダッシュボードへ移動','대시보드로 이동','انتقل إلى لوحة التحكم','डैशबोर्ड पर जाएं','Перейти в Панель Управления','Kontrol Paneline Git','Đi đến Bảng điều khiển','Ga naar Dashboard');
add('order_executed','Order Executed','Orden Ejecutada','Ordre Exécuté','Auftrag Ausgeführt','Ordem Executada','Ordine Eseguito','订单已执行','注文が実行されました','주문이 실행되었습니다','تم تنفيذ الأمر','आदेश निष्पादित','Ордер Выполнен','Emir Gerçekleştirildi','Lệnh Đã Thực hiện','Order Uitgevoerd');
add('investment_order_filled','Your investment order has been filled.','Su orden de inversión ha sido completada.','Votre ordre d\'investissement a été exécuté.','Ihr Investitionsauftrag wurde ausgeführt.','Sua ordem de investimento foi preenchida.','Il tuo ordine di investimento è stato eseguito.','您的投资订单已成交。','投資注文が約定されました。','투자 주문이 체결되었습니다.','تم تنفيذ أمر استثمارك.','आपका निवेश आदेश पूरा हो गया है।','Ваш инвестиционный ордер исполнен.','Yatırım emriniz gerçekleştirildi.','Lệnh đầu tư của bạn đã được khớp.','Uw beleggingsorder is uitgevoerd.');
add('total_value','Total Value','Valor Total','Valeur Totale','Gesamtwert','Valor Total','Valore Totale','总价值','合計価値','총 가치','القيمة الإجمالية','कुल मूल्य','Общая Стоимость','Toplam Değer','Tổng Giá trị','Totale Waarde');
add('execution_price','Execution Price','Precio de Ejecución','Prix d\'Exécution','Ausführungspreis','Preço de Execução','Prezzo di Esecuzione','执行价格','執行価格','체결 가격','سعر التنفيذ','निष्पादन मूल्य','Цена Исполнения','Gerçekleşme Fiyatı','Giá Thực hiện','Uitvoeringsprijs');
add('track_portfolio','Track your portfolio performance anytime.','Rastree el rendimiento de su cartera en cualquier momento.','Suivez les performances de votre portefeuille à tout moment.','Verfolgen Sie jederzeit die Performance Ihres Portfolios.','Acompanhe o desempenho da sua carteira a qualquer momento.','Tieni traccia delle prestazioni del tuo portafoglio in qualsiasi momento.','随时追踪您的投资组合表现。','いつでもポートフォリオのパフォーマンスを追跡してください。','언제든지 포트폴리오 성과를 추적하세요.','تتبع أداء محفظتك في أي وقت.','कभी भी अपने पोर्टफोलियो के प्रदर्शन को ट्रैक करें।','Отслеживайте эффективность вашего портфеля в любое время.','Portföyünüzün performansını istediğiniz zaman takip edin.','Theo dõi hiệu suất danh mục đầu tư của bạn mọi lúc.','Volg de prestaties van uw portefeuille altijd op.');
add('view_portfolio','View Portfolio','Ver Cartera','Voir le Portefeuille','Portfolio Ansehen','Ver Carteira','Visualizza Portafoglio','查看投资组合','ポートフォリオを表示','포트폴리오 보기','عرض المحفظة','पोर्टफोलियो देखें','Посмотреть Портфель','Portföyü Görüntüle','Xem Danh mục Đầu tư','Bekijk Portefeuille');
add('profile_updated','Profile Updated','Perfil Actualizado','Profil Mis à Jour','Profil Aktualisiert','Perfil Atualizado','Profilo Aggiornato','个人资料已更新','プロフィールが更新されました','프로필이 업데이트되었습니다','تم تحديث الملف الشخصي','प्रोफ़ाइल अपडेट की गई','Профиль Обновлен','Profil Güncellendi','Hồ sơ Đã Cập nhật','Profiel Bijgewerkt');
add('account_changes_confirm','This email is to confirm that recent changes have been made to your account profile.','Este correo es para confirmar que se han realizado cambios recientes en su perfil de cuenta.','Cet e-mail confirme que des modifications récentes ont été apportées à votre profil de compte.','Diese E-Mail bestätigt, dass kürzlich Änderungen an Ihrem Kontoprofil vorgenommen wurden.','Este e-mail é para confirmar que alterações recentes foram feitas no seu perfil de conta.','Questa email conferma che sono state apportate modifiche recenti al tuo profilo conto.','此邮件旨在确认您的账户资料近期有更改。','このメールは、アカウントプロフィールに最近変更が加えられたことを確認するものです。','이 이메일은 최근 계정 프로필에 변경 사항이 있었음을 확인하기 위한 것입니다.','هذا البريد الإلكتروني لتأكيد أنه تم إجراء تغييرات مؤخرًا على ملف تعريف حسابك.','यह ईमेल इस बात की पुष्टि करने के लिए है कि हाल ही में आपके खाता प्रोफ़ाइल में परिवर्तन किए गए हैं।','Это письмо подтверждает, что в вашем профиле аккаунта недавно были внесены изменения.','Bu e-posta, hesap profilinizde yakın zamanda değişiklikler yapıldığını teyit etmek içindir.','Email này để xác nhận rằng hồ sơ tài khoản của bạn gần đây đã có thay đổi.','Deze e-mail bevestigt dat er recent wijzigingen zijn aangebracht in uw accountprofiel.');
add('update_type','Update Type','Tipo de Actualización','Type de Mise à Jour','Aktualisierungstyp','Tipo de Atualização','Tipo di Aggiornamento','更新类型','更新タイプ','업데이트 유형','نوع التحديث','अपडेट प्रकार','Тип Обновления','Güncelleme Türü','Loại Cập nhật','Update Type');
add('contact_support','Contact Support','Contactar Soporte','Contacter le Support','Support Kontaktieren','Entrar em Contato com o Suporte','Contatta l\'Assistenza','联系客服','サポートに問い合わせ','지원팀에 문의','الاتصال بالدعم','सहायता से संपर्क करें','Связаться со Службой Поддержки','Destek ile İletişime Geçin','Liên hệ Hỗ trợ','Contact Ondersteuning');
add('go_to_paypal','Go to PayPal','Ir a PayPal','Aller sur PayPal','Zu PayPal Gehen','Ir para o PayPal','Vai su PayPal','前往PayPal','PayPalへ移動','PayPal로 이동','انتقل إلى PayPal','PayPal पर जाएं','Перейти в PayPal','PayPal\'a Git','Đi đến PayPal','Ga naar PayPal');
add('web_client','Web Client','Cliente Web','Client Web','Web-Client','Cliente Web','Client Web','网页客户端','Webクライアント','웹 클라이언ت','عميل الويب','वेब क्लाइंट','Веб-Клиент','Web İstemcisi','Máy khách Web','Web Client');
add('unknown','Unknown','Desconocido','Inconnu','Unbekannt','Desconhecido','Sconosciuto','未知','不明','알 수 없음','غير معروف','अज्ञात','Неизвестно','Bilinmeyen','Không xác định','Onbekend');
add('action_required_unread','Action Required: Unread Message','Acción Requerida: Mensaje No Leído','Action Requise : Message Non Lu','Aktion Erforderlich: Ungelesene Nachricht','Ação Necessária: Mensagem Não Lida','Azione Richiesta: Messaggio Non Letto','需要操作：未读消息','対応が必要：未読メッセージ','조치 필요: 읽지 않은 메시지','إجراء مطلوب: رسالة غير مقروءة','कार्रवाई आवश्यक: अपठित संदेश','Требуется действие: Непрочитанное сообщение','Eylem Gerekli: Okunmamış Mesaj','Yêu cầu Hành động: Tin nhắn Chưa đọc','Actie vereist: Ongelezen bericht');
add('unread_paypal_transfer','you have an unread message regarding your PayPal transfer.','tiene un mensaje no leído sobre su transferencia de PayPal.','vous avez un message non lu concernant votre transfert PayPal.','Sie haben eine ungelesene Nachricht bezüglich Ihrer PayPal-Überweisung.','você tem uma mensagem não lida sobre sua transferência do PayPal.','hai un messaggio non letto riguardante il tuo trasferimento PayPal.','您有一条关于PayPal转账的未读消息。','PayPal送金に関する未読メッセージがあります。','PayPal 송금에 관한 읽지 않은 메시지가 있습니다.','لديك رسالة غير مقروءة بخصوص تحويل PayPal الخاص بك.','आपके पास PayPal स्थानांतरण के बारे में एक अपठित संदेश है।','У вас есть непрочитанное сообщение о вашем переводе PayPal.','PayPal transferinizle ilgili okunmamış bir mesajınız var.','bạn có một tin nhắn chưa đọc liên quan đến chuyển khoản PayPal của mình.','u heeft een ongelezen bericht over uw PayPal-overboeking.');
add('review_message_confirm','Please review the message and confirm your payment to proceed with the transfer.','Por favor, revise el mensaje y confirme su pago para proceder con la transferencia.','Veuillez consulter le message et confirmer votre paiement pour procéder au transfert.','Bitte überprüfen Sie die Nachricht und bestätigen Sie Ihre Zahlung, um mit der Überweisung fortzufahren.','Por favor, revise a mensagem e confirme seu pagamento para prosseguir com a transferência.','Si prega di rivedere il messaggio e confermare il pagamento per procedere con il trasferimento.','请查看消息并确认您的付款以继续进行转账。','メッセージを確認し、送金を進めるためにお支払いを確認してください。','메시지를 검토하고 송금을 진행하려면 결제를 확인해 주세요.','يرجى مراجعة الرسالة وتأكيد الدفع للمتابعة في التحويل.','कृपया संदेश की समीक्षा करें और हस्तांतरण के लिए आगे बढ़ने के लिए अपना भुगतान पुष्टि करें।','Пожалуйста, ознакомьтесь с сообщением и подтвердите платеж, чтобы продолжить перевод.','Lütfen mesajı inceleyin ve transferi sürdürmek için ödemenizi onaylayın.','Vui lòng xem lại tin nhắn và xác nhận thanh toán của bạn để tiếp tục chuyển khoản.','Bekijk het bericht en bevestig uw betaling om door te gaan met de overboeking.');
add('view_message_confirm','View Message & Confirm','Ver Mensaje y Confirmar','Voir le Message et Confirmer','Nachricht Anzeigen & Bestätigen','Ver Mensagem e Confirmar','Visualizza Messaggio e Conferma','查看消息并确认','メッセージを表示して確認','메시지 보기 및 확인','عرض الرسالة وتأكيد','संदेश देखें और पुष्टि करें','Просмотреть Сообщение и Подтвердить','Mesajı Görüntüle ve Onayla','Xem Tin nhắn và Xác nhận','Bekijk bericht & Bevestig');
add('click_button_chat','Click the button below to view the full conversation and continue chatting with our team.','Haga clic en el botón de abajo para ver la conversación completa y continuar chateando con nuestro equipo.','Cliquez sur le bouton ci-dessous pour voir la conversation complète et continuer à discuter avec notre équipe.','Klicken Sie auf die Schaltfläche unten, um das vollständige Gespräch anzusehen und mit unserem Team weiterzuchatten.','Clique no botão abaixo para ver a conversa completa e continuar conversando com nossa equipe.','Clicca sul pulsante qui sotto per visualizzare la conversazione completa e continuare a chattare con il nostro team.','点击下面的按钮查看完整对话并继续与我们的团队聊天。','下のボタンをクリックして、完全な会話を表示し、チームとのチャットを続けてください。','아래 버튼을 클릭하여 전체 대화를 보고 당사 팀과 계속 채팅하세요.','انقر على الزر أدناه لعرض المحادثة الكاملة والاستمرار في الدردشة مع فريقنا.','पूरी बातचीत देखने और हमारी टीम के साथ चैट जारी रखने के लिए नीचे दिए गए बटन पर क्लिक करें।','Нажмите кнопку ниже, чтобы просмотреть полный разговор и продолжить общение с нашей командой.','Tam görüşmeyi görüntülemek ve ekibimizle sohbet etmeye devam etmek için aşağıdaki düğmeye tıklayın.','Nhấp vào nút bên dưới để xem cuộc trò chuyện đầy đủ và tiếp tục trò chuyện với nhóm của chúng tôi.','Klik op de onderstaande knop om het volledige gesprek te bekijken en verder te chatten met ons team.');
add('if_not_you_changes','If you did not make these changes, please contact support immediately.','Si no realizó estos cambios, comuníquese con soporte inmediatamente.','Si vous n\'avez pas apporté ces modifications, veuillez contacter le support immédiatement.','Wenn Sie diese Änderungen nicht vorgenommen haben, kontaktieren Sie bitte sofort den Support.','Se você não fez essas alterações, entre em contato com o suporte imediatamente.','Se non hai apportato queste modifiche, contatta immediatamente l\'assistenza.','如果您没有进行这些更改，请立即联系客服。','これらの変更を行っていない場合は、直ちにサポートにご連絡ください。','이러한 변경 사항을 하지 않으셨다면 즉시 지원팀에 문의하십시오.','إذا لم تقم بهذه التغييرات، يرجى الاتصال بالدعم على الفور.','यदि आपने ये परिवर्तन नहीं किए हैं, तो कृपया तुरंत सहायता से संपर्क करें।','Если вы не вносили эти изменения, немедленно свяжитесь со службой поддержки.','Bu değişiklikleri siz yapmadıysanız, lütfen hemen destekle iletişime geçin.','Nếu bạn không thực hiện những thay đổi này, vui lòng liên hệ hỗ trợ ngay lập tức.','Als u deze wijzigingen niet heeft aangebracht, neem dan onmiddellijk contact op met ondersteuning.');
add('manage_card_desc','Manage your card settings at any time from your wallet dashboard.','Gestione la configuración de su tarjeta en cualquier momento desde su panel de billetera.','Gérez les paramètres de votre carte à tout moment depuis votre tableau de bord de portefeuille.','Verwalten Sie Ihre Karteneinstellungen jederzeit über Ihr Wallet-Dashboard.','Gerencie as configurações do seu cartão a qualquer momento no painel da sua carteira.','Gestisci le impostazioni della tua carta in qualsiasi momento dalla dashboard del portafoglio.','随时从您的钱包仪表盘管理您的卡片设置。','いつでもウォレットダッシュボードからカード設定を管理できます。','지갑 대시보드에서 언제든지 카드 설정을 관리하세요.','أدر إعدادات بطاقتك في أي وقت من لوحة تحكم محفظتك.','कृपया कभी भी अपने वॉलेट डैशबोर्ड से अपने कार्ड सेटिंग्स का प्रबंधन करें।','Управляйте настройками своей карты в любое время из панели управления кошельком.','Cüzdan panelinizden istediğiniz zaman kart ayarlarınızı yönetin.','Quản lý cài đặt thẻ của bạn mọi lúc từ bảng điều khiển ví.','Beheer uw kaartinstellingen op elk moment vanaf uw portemonnee-dashboard.');
add('help_contact','Help & Contact','Ayuda y Contacto','Aide et Contact','Hilfe & Kontakt','Ajuda e Contato','Aiuto e Contatto','帮助与联系','ヘルプと問い合わせ','도움말 및 문의','المساعدة والاتصال','सहायता और संपर्क','Справка и Контакты','Yardım ve İletişim','Trợ giúp & Liên hệ','Help & Contact');
add('security','Security','Seguridad','Sécurité','Sicherheit','Segurança','Sicurezza','安全','セキュリティ','보안','الأمان','सुरक्षा','Безопасность','Güvenlik','Bảo mật','Beveiliging');
add('apps','Apps','Aplicaciones','Applications','Apps','Aplicativos','App','应用','アプリ','앱','تطبيقات','ऐप्स','Приложения','Uygulamalar','Ứng dụng','Apps');
add('learn_phishing','Learn to identify phishing','Aprenda a identificar phishing','Apprenez à identifier le hameçonnage','Lernen Sie, Phishing zu erkennen','Aprenda a identificar phishing','Impara a identificare il phishing','了解如何识别网络钓鱼','フィッシングの識別方法を学ぶ','피싱 식별 방법 배우기','تعلم التعرف على التصيد الاحتيالي','फिशिंग की पहचान करना सीखें','Научитесь распознавать фишинг','Oltalama saldırılarını tanımayı öğrenin','Tìm hiểu cách nhận biết lừa đảo','Leer phishing herkennen');
add('dont_reply_email','Please don\'t reply to this email. To get in touch with us, click','Por favor, no responda a este correo. Para comunicarse con nosotros, haga clic en','Veuillez ne pas répondre à cet e-mail. Pour nous contacter, cliquez sur','Bitte antworten Sie nicht auf diese E-Mail. Um mit uns Kontakt aufzunehmen, klicken Sie auf','Por favor, não responda a este e-mail. Para entrar em contato conosco, clique em','Si prega di non rispondere a questa e-mail. Per mettersi in contatto con noi, clicchi su','请勿回复此邮件。如需联系我们，请点击','このメールに返信しないでください。お問い合わせは、','이 이메일에 답장하지 마십시오. 당사에 문의하려면 다음을 클릭하십시오.','يرجى عدم الرد على هذا البريد الإلكتروني. للتواصل معنا، انقر على','कृपया इस ईमेल का जवाब न दें। हमसे संपर्क करने के लिए, क्लिक करें','Пожалуйста, не отвечайте на это письмо. Чтобы связаться с нами, нажмите на','Lütfen bu e-postaya yanıt vermeyin. Bizimle iletişime geçmek için','Vui lòng không trả lời email này. Để liên hệ với chúng tôi, nhấp vào','Reageer alstublieft niet op deze e-mail. Neem contact met ons op via');
add('not_sure_why','Not sure why you received this email?','¿No está seguro de por qué recibió este correo?','Vous ne savez pas pourquoi vous avez reçu cet e-mail?','Sind Sie sich nicht sicher, warum Sie diese E-Mail erhalten haben?','Não tem certeza de por que recebeu este e-mail?','Non sei sicuro del motivo per cui hai ricevuto questa e-mail?','不确定为什么收到此邮件？','このメールを受け取った理由がわかりませんか？','이 이메일을 받은 이유를 모르시겠나요؟','غير متأكد من سبب تلقيك هذا البريد الإلكتروني؟','इस ईमेल को प्राप्त करने का कारण निश्चित नहीं है?','Не уверены, почему получили это письмо?','Bu e-postayı neden aldığınızdan emin değil misiniz?','Không chắc tại sao bạn nhận được email này?','Weet u niet zeker waarom u deze e-mail heeft ontvangen?');
add('learn_more','Learn more','Más información','En savoir plus','Mehr erfahren','Saiba mais','Scopri di più','了解更多','詳細はこちら','더 알아보기','تعرف على المزيد','और जानें','Подробнее','Daha fazla bilgi','Tìm hiểu thêm','Meer informatie');
add('privacy','Privacy','Privacidad','Confidentialité','Datenschutz','Privacidade','Privacy','隐私','プライバシー','개인정보 보호','الخصوصية','गोपनीयता','Конфиденциальность','Gizlilik','Quyền riêng tư','Privacy');
add('support','Support','Soporte','Support','Support','Suporte','Supporto','支持','サポート','지원','الدعم','सहायता','Поддержка','Destek','Hỗ trợ','Ondersteuning');
add('need_help','Need help?','¿Necesita ayuda?','Besoin d\'aide?','Brauchen Sie Hilfe?','Precisa de ajuda?','Hai bisogno di aiuto?','需要帮助？','ヘルプが必要ですか？','도움이 필요하신가요؟','هل تحتاج إلى مساعدة؟','मदद चाहिए?','Нужна помощь?','Yardıma mı ihtiyacınız var?','Cần trợ giúp?','Hulp nodig?');
add('continue_live_chat','Continue live chat','Continuar chat en vivo','Continuer le chat en direct','Live-Chat fortsetzen','Continuar chat ao vivo','Continua chat dal vivo','继续实时聊天','ライブチャットを続ける','실시간 채팅 계속하기','متابعة الدردشة المباشرة','लाइव चैट जारी रखें','Продолжить живой чат','Canlı sohbete devam et','Tiếp tục trò chuyện trực tiếp','Ga door met live chat');
add('paypal_fraud_prevention','PayPal is committed to preventing fraudulent emails. Emails from PayPal will always contain your full name.','PayPal se compromete a prevenir correos electrónicos fraudulentos. Los correos de PayPal siempre contendrán su nombre completo.','PayPal s\'engage à prévenir les e-mails frauduleux. Les e-mails de PayPal contiendront toujours votre nom complet.','PayPal setzt sich dafür ein, betrügerische E-Mails zu verhindern. E-Mails von PayPal enthalten immer Ihren vollständigen Namen.','O PayPal está comprometido em prevenir e-mails fraudulentos. Os e-mails do PayPal sempre conterão seu nome completo.','PayPal si impegna a prevenire le email fraudolente. Le email di PayPal conterranno sempre il tuo nome completo.','PayPal致力于防止欺诈性电子邮件。来自PayPal的邮件将始终包含您的全名。','PayPalは詐欺メールの防止に取り組んでいます。PayPalからのメールには必ず氏名が記載されます。','PayPal은 사기성 이메일 방지를 위해 노력하고 있습니다. PayPal에서 보내는 이메일에는 항상 전체 이름이 포함됩니다.','يلتزم PayPal بمنع رسائل البريد الإلكتروني الاحتيالية. ستتضمن رسائل PayPal دائمًا اسمك الكامل.','PayPal धोखाधड़ी वाले ईमेलों को रोकने के लिए प्रतिबद्ध है। PayPal के ईमेल में हमेशा आपका पूरा नाम होगा।','PayPal стремится предотвращать мошеннические письма. В письмах от PayPal всегда будет указано ваше полное имя.','PayPal, dolandırıcı e-postaları önlemeye kararlıdır. PayPal\'dan gelen e-postalarda her zaman tam adınız yer alacaktır.','PayPal cam kết ngăn chặn các email gian lận. Email từ PayPal sẽ luôn chứa họ tên đầy đủ của bạn.','PayPal zet zich in om frauduleuze e-mails te voorkomen. E-mails van PayPal bevatten altijd uw volledige naam.');
add('method','Method','Método','Méthode','Methode','Método','Metodo','方法','方法','방법','الطريقة','तरीका','Метод','Yöntem','Phương thức','Methode');
add('view_reply_continue','View Reply & Continue','Ver Respuesta y Continuar','Voir la Réponse et Continuer','Antwort Ansehen & Fortfahren','Ver Resposta e Continuar','Visualizza Risposta e Continua','查看回复并继续','返信を表示して続行','답장 보기 및 계속','عرض الرد والمتابعة','उत्तर देखें और जारी रखें','Просмотреть Ответ и Продолжить','Yanıtı Görüntüle ve Devam Et','Xem Phản hồi và Tiếp tục','Bekijk Antwoord en Ga door');
add('new_message_support','You have a new message from support.','Tiene un nuevo mensaje de soporte.','Vous avez un nouveau message du support.','Sie haben eine neue Nachricht vom Support.','Você tem uma nova mensagem do suporte.','Hai un nuovo messaggio dall\'assistenza.','您有一条来自客服的新消息。','サポートからの新しいメッセージがあります。','지원팀의 새로운 메시지가 있습니다.','لديك رسالة جديدة من الدعم.','आपको सहायता से एक नया संदेश मिला है।','У вас новое сообщение от поддержки.','Destekten yeni bir mesajınız var.','Bạn có tin nhắn mới từ hỗ trợ.','U heeft een nieuw bericht van ondersteuning.');
add('unread_message_from_support','Unread Message from Support','Mensaje No Leído del Soporte','Message Non Lu du Support','Ungelesene Nachricht vom Support','Mensagem Não Lida do Suporte','Messaggio Non Letto dall\'Assistenza','来自客服的未读消息','サポートからの未読メッセージ','지원팀의 읽지 않은 메시지','رسالة غير مقروءة من الدعم','सहायता से अपठित संदेश','Непрочитанное Сообщение от Поддержки','Destekten Okunmamış Mesaj','Tin nhắn Chưa đọc từ Hỗ trợ','Ongelezen bericht van Ondersteuning');
add('welcome_to','Welcome to','Bienvenido a','Bienvenue à','Willkommen bei','Bem-vindo ao','Benvenuto in','欢迎来到','ようこそ','에 오신 것을 환영합니다','مرحباً بك في','में आपका स्वागत है','Добро пожаловать в','Hoş Geldiniz','Chào mừng đến','Welkom bij');
add('status_success','Success','Éxito','Succès','Erfolg','Sucesso','Successo','成功','成功','성공','نجاح','सफलता','Успех','Başarı','Thành công','Succes');
add('status_pending','Pending','Pendiente','En Attente','Ausstehend','Pendente','In Sospeso','待处理','保留中','대기 중','معلق','लंबित','В Ожидании','Beklemede','Đang chờ xử lý','In Afwachting');
add('status_failed','Failed','Fallido','Échoué','Fehlgeschlagen','Falhou','Fallito','失败','失敗','실패','فشل','विफल','Неудача','Başarısız','Thất bại','Mislukt');
add('status_on_hold','On Hold','En Espera','En Attente','Zurückgestellt','Em Espera','In Attesa','暂留','保留中','보류 중','معلق','होल्ड पर','На Удержании','Beklemede','Tạm giữ','In Wacht');
add('status_processing','Processing','Procesando','En Cours de Traitement','In Bearbeitung','Processando','In Elaborazione','处理中','処理中','처리 중','قيد المعالجة','प्रसंस्करण','Обработка','İşleniyor','Đang xử lý','In Behandeling');
add('status_completed','Completed','Completado','Terminé','Abgeschlossen','Concluído','Completato','已完成','完了','완료','مكتمل','पूरा हुआ','Завершено','Tamamlandı','Hoàn thành','Voltooid');
add('na','N/A','N/D','N/D','N/V','N/A','N/D','不适用','該当なし','해당 없음','غير متاح','लागू नहीं','Н/Д','N/A','Không áp dụng','N/B');
add('notification','Notification','Notificación','Notification','Benachrichtigung','Notificação','Notifica','通知','通知','알림','إشعار','सूचना','Уведомление','Bildirim','Thông báo','Melding');
add('customer_center','Customer Center','Centro de Atención','Centre Clientèle','Kundencenter','Centro de Atendimento','Centro Assistenza Clienti','客户中心','カスタマーセンター','고객 센터','مركز خدمة العملاء','ग्राहक केंद्र','Центр Обслуживания','Müşteri Merkezi','Trung tâm Chăm sóc Khách hàng','Klantenservice');
add('call','Call','Llamar','Appeler','Anruf','Chamada','Chiama','电话','電話','전화','اتصال','कॉल','Звонок','Arama','Gọi','Bel');
add('checking','Checking','Cuenta Corriente','Compte Courant','Girokonto','Conta Corrente','Conto Corrente','支票账户','当座預金','당좌 예금','جاري','चेकिंग','Текущий Счёт','Vadesiz','Thanh toán','Betalen');
add('company_payroll','Company Payroll','Nómina de la Empresa','Paie de l\'Entreprise','Firmen-Payroll','Folha de Pagamento da Empresa','Paghe Aziendali','公司工资单','会社給与','회사 급여','كشف رواتب الشركة','कंपनी वेतन','Зарплатная Ведомость','Şirket Maaş Bordrosu','Lương Công ty','Bedrijfssalaris');
add('support_team','Support Team','Equipo de Soporte','Équipe de Support','Support-Team','Equipe de Suporte','Team di Supporto','支持团队','サポートチーム','지원팀','فريق الدعم','सहायता टीम','Команда Поддержки','Destek Ekibi','Đội ngũ Hỗ trợ','Ondersteuningsteam');

export function t(key: string, lang?: string): string {
  const l = (lang || DEFAULT_LANG).toLowerCase() as LangCode;
  const entry = DICT[key];
  if (!entry) return key;
  return entry[l] || entry[DEFAULT_LANG] || key;
}

export function getLanguageDir(lang?: string): 'ltr' | 'rtl' {
  const found = SUPPORTED_LANGUAGES.find(l => l.code === (lang || DEFAULT_LANG).toLowerCase());
  return (found?.dir || 'ltr') as 'ltr' | 'rtl';
}

export function getLanguageByCode(code: string) {
  return SUPPORTED_LANGUAGES.find(l => l.code === code.toLowerCase());
}
